Add mobile instructions
bounswe/bounswe2024group5 pull request #338
Opened 2024-10-21 22:29 UTC by ebrarkiziloglu

This PR adds mobile build instructions

2024-10-22 07:15 UTC, HutkuC requested changes

2024-10-22 07:37 UTC, ebrarkiziloglu commented on instructions.md
> +## Instractions for installation
You're right, I removed the unnecessary header.

2024-10-22 08:21 UTC, semihYILMAZ37 commented
it seems alright.

2024-10-24 16:09 UTC, HutkuC approved these changes

2024-10-24 16:10 UTC, merged